### ISSUE TITLE
アプリの仕様を考える

### ISSUE THREAD

**Issue by 4geru** [4geru/yowtag#11]
### Discussed in https://github.com/4geru/yowtag/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **4geru** July 29, 2022</sup>
## 考えていること / 悩んでいること

仕様を作る上で、必要なことをまとめる。

- ページ遷移
- 使いたい API について調査</div>

### TODO
- [ ] https://github.com/4geru/yowtag/issues/12
- [ ] https://github.com/4geru/yowtag/issues/13
- [x] https://github.com/4geru/yowtag/issues/14
